# Generated by Django 3.2.11 on 2022-01-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taschengeldapp', '0002_auto_20220105_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buchung',
            old_name='ausgabe_einnahme',
            new_name='einnahme',
        ),
        migrations.RemoveField(
            model_name='konto',
            name='konto_inhaber',
        ),
        migrations.AddField(
            model_name='buchung',
            name='ausgabe',
            field=models.BooleanField(default=True),
        ),
    ]
