# Generated by Django 3.2.11 on 2022-01-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taschengeldapp', '0004_auto_20220105_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buchung',
            name='ausgabe',
        ),
    ]
