# Generated by Django 4.0 on 2022-01-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taschengeldapp', '0005_remove_buchung_ausgabe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchung',
            name='buchungsdatum',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='konto',
            name='konto_erstellungsdatum',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
