# Generated by Django 4.0 on 2022-01-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taschengeldapp', '0006_alter_buchung_buchungsdatum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buchung',
            options={'verbose_name_plural': 'Buchungen'},
        ),
        migrations.AlterModelOptions(
            name='konto',
            options={'verbose_name_plural': 'Konten'},
        ),
    ]
