# Generated by Django 3.2.11 on 2022-01-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Konto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konto_name', models.CharField(max_length=100)),
                ('konto_inhaber', models.CharField(max_length=100)),
                ('aktueller_kontostand', models.FloatField()),
                ('konto_erstellungsdatum', models.DateTimeField(verbose_name='erstellt am')),
            ],
        ),
        migrations.CreateModel(
            name='Buchung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.CharField(max_length=200)),
                ('betrag', models.FloatField()),
                ('ausgabe_einnahme', models.BooleanField(default=False)),
                ('buchungsdatum', models.DateTimeField(verbose_name='erstellt am')),
                ('konto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taschengeldapp.konto')),
            ],
        ),
    ]
