# Generated by Django 3.2.11 on 2022-01-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taschengeldapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchung',
            name='betrag',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='konto',
            name='aktueller_kontostand',
            field=models.FloatField(default=0),
        ),
    ]
