# Generated by Django 3.2.12 on 2022-04-14 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taschengeldapp', '0008_alter_buchung_beschreibung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchung',
            name='konto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buchungen', to='taschengeldapp.konto'),
        ),
    ]
